jwt:
  secret: 'asdfghjkl123456789987654321lkjhgfdsa'

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fresher_management
    username: van
    password: SQLWorkbench
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    username: conglvfx20485@funix.edu.vn
    password: FuNi20485
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Show message when query error
logging:
  level:
    org:
      springframework:
        security: DEBUG
