jwt:
  secret: 'asdfghjkl123456789987654321lkjhgfdsa'

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fresher_management
    username: van
    password: SQLWorkbench
#    url: jdbc:postgresql://dpg-civth96nqql48o2sot5g-a.singapore-postgres.render.com/fresher_management
#    username: demo_project_90zq_user
#    password: wEQXvZhEtbzQ4Qe47aVoOlMIXYTUVUm4

  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      springframework:
        security: DEBUG
